name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get current date and time
      id: date
      run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ecomm-analytics:${{ steps.date.outputs.timestamp }}

    - name: Update image tag in manifests/app.yaml
      run: |
        IMAGE="${{ secrets.DOCKER_USERNAME }}/ecomm-analytics:${{ steps.date.outputs.timestamp }}"
        echo "Updating image to: $IMAGE"
        sed -i "s|image:.*|image: $IMAGE|g" manifests/app.yaml

    # Optional: Commit the updated manifest back to the repo
    - name: Commit and push updated manifest
      run: |
        git config --global user.name "Arunvel Arunachalam"
        git config --global user.email "aryan.arunachalam@gmail.com"
        git add manifests/app.yaml
        git commit -m "Update image tag to ${{ steps.date.outputs.timestamp }}"
        git remote set-url origin https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ github.repository }}
        git push origin HEAD:main
